Repository SU-SWS/eirh-subtheme, pull requests merged in 2024-03, with the labels that each got.

#10 EIRH-55 | @rebeccahongsf | scaffold facetfilter component
  src/eventshub/package-lock.json
  src/eventshub/package.json
  src/eventshub/src/App.tsx
  src/eventshub/src/component/Autocomplete/Autocomplete.tsx
  src/eventshub/src/component/Cta/Cta.styles.ts
  src/eventshub/src/component/Cta/Cta.tsx
  src/eventshub/src/component/Cta/index.ts
  src/eventshub/src/component/CustomHits/CustomHits.tsx
  src/eventshub/src/component/CustomHits/index.ts
  src/eventshub/src/component/FilterChips/FilterChips.tsx
  src/eventshub/src/component/FilterChips/index.ts
  src/eventshub/src/component/FlexBox/FlexBox.styles.ts
  src/eventshub/src/component/FlexBox/FlexBox.tsx
  src/eventshub/src/component/FlexBox/FlexBox.types.ts
  src/eventshub/src/component/FlexBox/index.ts
  src/eventshub/src/component/Grid/Grid.styles.ts
  src/eventshub/src/component/Grid/Grid.tsx
  src/eventshub/src/component/Grid/Grid.types.ts
  src/eventshub/src/component/Grid/index.ts
  src/eventshub/src/component/Search/Search.tsx
  src/eventshub/src/component/Search/index.ts
  src/eventshub/src/component/SearchFilter/SearchFilter.tsx
  src/eventshub/src/component/SearchFilter/index.ts
  src/eventshub/src/component/SearchItem/PolicySearchItem.tsx
  src/eventshub/src/component/SearchItem/SearchItem.tsx
  src/eventshub/src/component/SearchItem/TypeList.tsx
  src/eventshub/src/component/SearchItem/VendorSearchItem.tsx
  src/eventshub/src/component/SearchItem/VenueSearchItem.tsx
  src/eventshub/src/component/SearchItem/index.ts
  src/eventshub/src/component/SearchTab/SearchTab.tsx
  src/eventshub/src/component/SearchTab/index.ts
  src/eventshub/src/main.tsx
  src/eventshub/src/redux/slices/algoliaFilterDataSlice.ts
  src/eventshub/src/redux/slices/filtersSlice.ts
  src/eventshub/src/redux/slices/searchTypeSlice.ts
  src/eventshub/src/redux/store.ts
  src/eventshub/src/utilities/algoliaConfig.ts
  src/eventshub/src/utilities/algoliaFiltersData.ts
  src/eventshub/src/utilities/datasource.ts
  src/eventshub/src/utilities/getFilterData.ts
Labels: size/l

#13 nojira | @rebeccahongsf | build dist
  src/eventshub/dist/eventshub.js
  src/eventshub/dist/index.css
  src/eventshub/src/component/FlexBox/FlexBox.tsx
  src/eventshub/src/component/Grid/Grid.tsx
Labels: size/xs

#14 NoJira: Fixups for the Drupal Theme
  .github/workflows/label.yml
  dist/css/ckeditor5.css
  dist/css/main.css
  doc/architecture/decisions/0003-css-approach-for-eventshub-with-tw-in-the-subtheme.md
  eirh_subtheme.info.yml
  eirh_subtheme.libraries.yml
  package-lock.json
  package.json
  src/assets/.gitkeep
  src/config.js
  src/eventshub/.adr-dir
  src/eventshub/dist/eventshub.js
  src/eventshub/dist/index.css
  src/eventshub/src/component/Cta/Cta.styles.ts
  src/eventshub/src/component/CustomHits/CustomHits.tsx
  src/eventshub/src/component/FilterChips/FilterChips.tsx
  src/eventshub/src/component/FlexBox/FlexBox.styles.ts
  src/eventshub/src/component/FlexBox/FlexBox.tsx
  src/eventshub/src/component/Grid/Grid.styles.ts
  src/eventshub/src/component/Grid/Grid.tsx
  src/eventshub/src/component/Search/Search.tsx
  src/eventshub/src/component/SearchFilter/SearchFilter.tsx
  src/eventshub/src/component/SearchItem/VenueSearchItem.tsx
  src/eventshub/src/component/Typography/Paragraph.tsx
  src/eventshub/src/component/Typography/SrOnlyText.tsx
  src/eventshub/src/component/Typography/Text.tsx
  src/eventshub/src/component/Typography/typography.styles.ts
  src/eventshub/src/index.css
  src/eventshub/src/utilities/datasource.ts
  src/eventshub/tailwind.config.ts
  src/scss/base/index.scss
  src/scss/ckeditor5.scss
  src/scss/components/index.scss
  src/scss/layout/index.scss
  src/scss/main.scss
  src/scss/print/index.scss
  src/scss/state/index.scss
  src/scss/theme/_button.scss
  src/scss/theme/_cta.scss
  src/scss/theme/index.scss
  src/scss/utilities/index.scss
  src/scss/utilities/mixins/_buttons.scss
  src/scss/utilities/mixins/_cta.scss
  src/scss/utilities/mixins/_link-icon.scss
  src/scss/utilities/mixins/index.scss
  src/scss/utilities/variables/_colors.scss
  src/scss/utilities/variables/index.scss
  templates/.gitkeep
  templates/node--16.html.twig
  webpack.config.js
  yarn.lock
Labels: size/xl
